In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [9]:
X=df[['Age','EstimatedSalary']] # or  X=df.iloc[:[2,3]]
Y=df['Purchased'] # or Y=df.iloc[:,[-1]]

In [12]:
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [13]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state=0)
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
X_train

array([[ 0.58164944, -0.89371129],
       [-0.60673761,  1.46457049],
       [-0.01254409, -0.56155893],
       [-0.60673761,  1.79672285],
       [ 1.37390747, -1.45837031],
       [ 1.47293972,  1.03277242],
       [ 0.08648817, -0.82728082],
       [-0.01254409, -0.22940657],
       [-0.21060859, -0.56155893],
       [-0.21060859, -0.16297609],
       [-0.30964085, -1.3587246 ],
       [-0.30964085, -0.56155893],
       [ 0.38358493,  0.13596103],
       [ 0.8787462 , -0.59477417],
       [ 2.06713324, -1.22586366],
       [ 1.07681071, -0.09654562],
       [ 0.68068169,  1.69707714],
       [-0.70576986,  0.66740482],
       [ 0.77971394,  0.43489816],
       [ 0.8787462 , -0.52834369],
       [-1.20093113, -1.65766173],
       [ 2.1661655 ,  0.99955718],
       [-0.01254409,  1.1988486 ],
       [ 0.18552042,  1.13241812],
       [ 0.38358493, -0.46191322],
       [-0.30964085, -0.29583704],
       [ 0.97777845, -0.86049606],
       [ 0.97777845,  1.76350762],
       [-0.01254409,

In [16]:
X_test

array([[-0.80480212,  0.60097434],
       [-0.01254409, -0.56155893],
       [-0.30964085,  0.20239151],
       [-0.80480212,  0.33525245],
       [-0.30964085, -0.56155893],
       [-1.10189888, -1.49158555],
       [-0.70576986, -1.65766173],
       [-0.21060859,  2.02922951],
       [-1.99318916, -0.03011515],
       [ 0.8787462 , -0.79406558],
       [-0.80480212, -0.59477417],
       [-1.00286662, -0.39548275],
       [-0.11157634, -0.39548275],
       [ 0.08648817,  0.26882198],
       [-1.79512465,  0.56775911],
       [-0.60673761,  1.36492478],
       [-0.11157634,  0.26882198],
       [-1.89415691,  0.53454387],
       [ 1.67100423,  1.66386191],
       [-0.30964085, -1.42515507],
       [-0.30964085, -0.66120464],
       [ 0.8787462 ,  2.02922951],
       [ 0.28455268, -0.52834369],
       [ 0.8787462 ,  1.06598765],
       [-1.49802789, -1.25907889],
       [ 1.07681071,  1.9295838 ],
       [-1.00286662,  0.60097434],
       [-0.90383437,  0.36846769],
       [-0.11157634,

In [17]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)
y_pred = lr.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

#  Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,y_pred)
cm

array([[65,  3],
       [ 8, 24]], dtype=int64)

In [21]:
acc=accuracy_score(Y_test,y_pred)
acc

0.89

In [ ]:
from sklearn.metrics import precision_score
prec=precision_score(Y_test,y_pred)
prec

In [ ]:
from sklearn.metrics import recall_score
recall=recall_score(Y_test,y__pred)